apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: dapr-test-pubsub
  namespace: dapr-test
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: connectionString
    value: "amqp://admin:password@rabbitmq:5672"
  - name: durable
    value: "false"
  - name: deletedWhenUnused
    value: "false"
  - name: autoAck
    value: "true"
  - name: reconnectWait
    value: "0"
  - name: concurrency
    value: parallel
