apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: dapr-test
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis:6379
  - name: keyPrefix
    value: none

---

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: privatestatestore
  namespace: dapr-test
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis:6379

---

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: actorsstatestore
  namespace: dapr-test
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis:6379
  - name: actorStateStore 
    value: "true"
