apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher
  namespace: dapr-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: publisher
  template:
    metadata:
      labels:
        app: publisher
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "publisher"
        dapr.io/app-port: "5000"  # Adjust to your service port
    spec:
      containers:
        - name: publisher
          image: cr.maks-it.com/dapr-test/subscriber:latest
          ports:
            - containerPort: 5000  # Match your internal app port

---

apiVersion: v1
kind: Service
metadata:
  name: publisher-service
  namespace: dapr-test
spec:
  selector:
    app: publisher
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000  # Match the internal port of the publisher service

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriber
  namespace: dapr-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscriber
  template:
    metadata:
      labels:
        app: subscriber
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "subscriber"
        dapr.io/app-port: "5000"  # Adjust to match the subscriber service port
    spec:
      containers:
        - name: subscriber
          image: cr.maks-it.com/dapr-test/subscriber:latest
          ports:
            - containerPort: 5000  # Match the internal port of the subscriber service
